spring:
  application:
    name: service2
server:
  port: 8602
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  zipkin:
    base-url: http://localhost:9411
