spring:
  application:
    name: service1
server:
  port: 8601
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  zipkin:
    base-url: http://localhost:9411